### ISSUE TITLE
Problems starting on C1

### ISSUE THREAD

**Issue by Kondra007** [fporter/limelight-odroid#5]
Hello. I managed to build limelight for Odroid (btw, you forgot to add **--enable-avresample** to configure, because this lib is needed when running scripts) 

Finally, I managed to start **limelight-linarm.jar** with parameters **-host 192.168.1.33**, where 192.168.1.33 is my PC with GFE turned on. However, I'm getting this error:

```
odroid@odroid:~$ java -jar limelight-linarm.jar -host 192.168.1.33
Apr 12, 2015 10:21:22 PM com.limelight.LimeLog info
INFO: Reading Preferences
Apr 12, 2015 10:21:23 PM com.limelight.LimeLog info
INFO: Writing Preferences
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:342)
        at com.simontuffs.onejar.Boot.main(Boot.java:168)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:535)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:174)
        at com.limelight.gui.StreamFrame.<init>(Unknown Source)
        at com.limelight.Limelight.startUp(Unknown Source)
        at com.limelight.Limelight.parseCommandLine(Unknown Source)
        at com.limelight.Limelight.main(Unknown Source)
        ... 6 more
```

**Comment by Kondra007** [comment]
**UPDATE**: Fixed it with ** export DISPLAY=:0.0 **

Now it requires GFE 2.1.1 or later...(I have 2.4.1.21)

**Comment by Kondra007** [comment]
**UPDATE 2**: Strange error with libavcodec.so.50 (see photos below)

http://i.imgur.com/Vu7om37.jpg
and 
http://i.imgur.com/S0ojCWW.jpg

**Comment by Kondra007** [comment]
**UPDATE 3:**
After running **ldconfig -v** command, new error is:
http://i.imgur.com/uTxO1v2.jpg

PS. I'm writing all steps to allow anyone reproduce them and, maybe, fix problem.

**Comment by fporter** [comment]
Have you tried the following in a terminal?
```
$ export LD_LIBRARY_PATH=/usr/local/lib/
$ java -jar limelight-arm.jar
```

I'm looking into what it will take for the new GFE, i currently have it compiling for and pairing with GFE 2.4 but the latest commits introduce JOGL, which is causing me issues. Although the last update before JOGL may work for the time being.

**Comment by Kondra007** [comment]
@fporter yes, of course, I did it!

**Comment by fporter** [comment]
I have updated the Readme.md with the complete steps taken to get it running on Odroid-C1 (from initial unboxing). I tested it with the latest GFE (2.4.1) and got it working. Hopefully it helps.

**Comment by Kondra007** [comment]
@fporter thanks, I'll try it tomorrow

**Comment by MasterGroosha** [comment]
@fporter I've finally tried your new method and it works! 
However, it's completely unplayable due to freezes and ~45-65 ms latency even with Ethernet connection.

This is strange, because I've seen perfect limelight working on Raspberry Pi, which is less powerfull than C1. Maybe something wrong with drivers?
